#!/bin/bash
set -xeuo pipefail

manifestdir=${1:-/usr/share/doc/bootc-base-imagectl/manifests}

mkdir -p "$manifestdir/base-images"
for image in minimal standard; do
    if [ -f $image.yaml ]; then
        cp -a $image.yaml "$manifestdir/base-images/"
    fi
done
# Bluefin/Aurora specific
ln -sf standard.yaml "$manifestdir/base-images/default.yaml"

mkdir -p "$manifestdir/packages"
# Map gnome -> silverblue-like (cosmic-atomic), kde -> kinoite-like
for image in gnome kde; do
    cp -a $image.yaml "$manifestdir/"
    # If we had package splits, we would copy them here.
    # Currently bluefin seems to have single manifests.
done

cp -a common-base.yaml "$manifestdir/"
cp -a aurora-common.yaml "$manifestdir/"
# cp -a packages/common.yaml $manifestdir/packages/ # Not present

# Includes
if [ -d includes ]; then
    cp -r includes "$manifestdir/"
fi

# Set default
ln -sf gnome.yaml "$manifestdir/default.yaml"
